language: go
sudo: false

go:
  - 1.6.4

notifications:
  on_success: never
  on_failure: never

addons:
  apt:
    packages:
    - libpcap-dev
    - libaspell-dev
    - libhunspell-dev

before_install:
 - go get -v github.com/chzchzchz/goword

script:
 - ./test
